image:
  tag: d850195e3aa85205e44afa4ce11e5689174c2cd6

ingressPrefix: int
ingressPgWebPrefix: int

ingressKafkaUIPrefix: int

kafkaUI:
  clusterName: scpi-cluster
  bootstrapServers: kafka-svc.kafka.svc.cluster.local:9092
  zookeeper: zookeeper.kafka.svc.cluster.local:2181

application:
  environment: int
