kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - scpi-inv-int.yml
  - scpi-inv-qua.yml
  - scpi-doc-validation-int.yml
  - scpi-doc-validation-qua.yml
  - argocd.yml
  - cert-manager.yml
  - external-dns.yml
  - jenkins.yml
  - keycloak.yml
  - sonarqube.yml
  - minio.yml
  - matomo.yml
  - harbor.yml
  - kafka.yml
  - monitoring.yml
  - n8n.yml

