apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: logging
data:
  loki-config.yaml: |
    auth_enabled: false
    ingester:
      chunk_idle_period: 3m
      max_chunk_age: 1h
      max_streams_per_user: 10000
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    server:
      http_listen_port: 3100
      log_level: info
    storage_config:
      filesystem:
        directory: /loki/chunks
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        shared_store: filesystem
        cache_location: /loki/boltdb-shipper-cache
    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h