apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: matomo
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:11.4
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: mariadb-root-password
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: mariadb-user
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: mariadb-password
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: mariadb-database
          ports:
            - containerPort: 3306
