image:
  tag: ad1f380a0479d789a50987e549769092ef6283b6

ingressPrefix: qua
ingressPgWebPrefix: qua

ingressKafkaUIPrefix: qua

kafkaUI:
  clusterName: scpi-cluster
  bootstrapServers: kafka-svc.kafka.svc.cluster.local:9092
  zookeeper: zookeeper.kafka.svc.cluster.local:2181

application:
  environment: qua
