image:
  tag: 93a4ab6e4ada792fbe0c22a7fa2c44aaa6f7dd3e

ingressPrefix: qua
ingressPgWebPrefix: qua

ingressKafkaUIPrefix: qua

kafkaUI:
  clusterName: scpi-cluster
  bootstrapServers: kafka-svc.kafka.svc.cluster.local:9092
  zookeeper: zookeeper.kafka.svc.cluster.local:2181

application:
  environment: qua
