apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
spec:
  generators:
    - git:
        repoURL: "https://github.com/mchekini-check-consulting/scpi-inv-argocd"
        revision: main
        directories:
          - path: '10-operators/*/prd'
  template:
    metadata:
      name: '{{ path[1] }}-operator'
    spec:
      project: default
      source:
        repoURL: "https://github.com/mchekini-check-consulting/scpi-inv-argocd"
        targetRevision: main
        path: '{{ path }}'
        kustomize:
          buildOptions: --enable-helm
      destination:
        name: in-cluster
        namespace: '{{ path[1] }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true