apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt
  secretName: minio-tls
  dnsNames:
    - minio.check-consulting.net
  usages:
    - digital signature
    - key encipherment