apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui-qua
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
    - hosts:
        - qua.kafka-ui.check-consulting.net
      secretName: kafka-ui-qua-tls
  rules:
    - host: qua.kafka-ui.check-consulting.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-ui
                port:
                  number: 8080
